##default adam config
#optimizer/adam.yml
#https://docs.pytorch.org/docs/stable/generated/torch.optim.Adam.html
_target_: torch.optim.Adam
lr: 0.001
betas: [0.9, 0.999] #default values for Adam
weight_decay: 0.0001