name: tvattention-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - scikit-learn
  - pillow
  - scikit-image
  - matplotlib
  - seaborn
  - tqdm
  - cvxpy
  - hydra-core
  - omegaconf
  - mlflow
  - optuna
  - ipykernel
  - cmake
  - cffi
  - pip:
      - ray[tune,air,dashboard]
      - albumentations
      - cvxpylayers
      - torchxrayvision
