#optuna set up for basic unet
#sweeper/basicUnet.yaml
# https://hydra.cc/docs/plugins/optuna_sweeper/
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 654321
  consider_prior: true
  prior_weight: 1.0
  consider_magic_clip: true
  consider_endpoints: false
  n_startup_trials: 10
  n_ei_candidates: 24
  multivariate: false
  warn_independent_sampling: true
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction: maximize
storage: null
study_name: UnetBasic
n_trials: 120
n_jobs: 1
max_failure_rate: 0.0

params:
  optimizer.lr: range(0.0001, 0.001, step=0.0001)
  optimizer.weight_decay: range(0.0, 0.0001, step=0.00001)
  train.batch_size: choice(64,128,256,512) #512 is an option for b200
  train.epochs: choice(25,50,75,100)




