#config.yaml (main orchestrator)

defaults:
  - model: Unet
  #- dataset:
  - train: default
  - optimizer: adam
  - logger: mlflow
  - override hydra/sweeper: basicUnet
  - _self_


seed: 654321

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: "${model.name}"
